apiVersion: v2
name: kafka-ui
description: A Helm chart for deploying Kafka UI (Kafbat) with Strimzi SCRAM-SHA-512 authentication
type: application
version: 0.2.0
appVersion: "v1.5.0"
kubeVersion: ">=1.27.0-0"
home: https://github.com/bmscomp/kates
sources:
  - https://github.com/bmscomp/kates
  - https://github.com/kafbat/kafka-ui
maintainers:
  - name: bmscomp
    url: https://github.com/bmscomp
keywords:
  - kafka
  - kafka-ui
  - kafbat
  - monitoring
  - strimzi
  - dashboard
