apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-ui.fullname" . }}-config
  namespace: {{ include "kafka-ui.namespace" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
data:
  config.yml: |
    kafka:
      clusters:
        - name: {{ .Values.kafka.clusterName }}
          bootstrapServers: {{ include "kafka-ui.bootstrapServers" . }}
          properties:
            {{- if .Values.kafka.tls.enabled }}
            security.protocol: SASL_SSL
            {{- else }}
            security.protocol: SASL_PLAINTEXT
            {{- end }}
            sasl.mechanism: SCRAM-SHA-512
            sasl.jaas.config: >-
              org.apache.kafka.common.security.scram.ScramLoginModule required
              username="{{ .Values.kafkaUser.name }}"
              password="${KAFKA_UI_PASSWORD}";
            {{- if .Values.kafka.tls.enabled }}
            ssl.truststore.type: PEM
            {{- end }}

    auth:
      type: {{ .Values.auth.type | default "DISABLED" }}
    management:
      health:
        ldap:
          enabled: false
