{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  namespace: {{ include "kafka-ui.namespace" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka-ui.selectorLabels" . | nindent 6 }}
{{- end }}
