{{- if and .Values.auth.enabled (eq .Values.auth.type "LOGIN_FORM") }}
{{- $secretName := .Values.auth.passwordSecret }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $secret }}
  password: {{ index $secret.data "password" }}
  {{- else }}
  password: {{ "admin" | b64enc }}
  {{- end }}
{{- end }}
