{{- if and .Values.metrics.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
{{- $sm := .Values.metrics.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  namespace: {{ include "kafka-ui.namespace" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kafka-ui.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "kafka-ui.namespace" . }}
  endpoints:
    - port: http
      path: {{ $sm.path | default "/actuator/prometheus" }}
      interval: {{ $sm.interval | default "30s" }}
      {{- with $sm.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: {{ $sm.honorLabels | default false }}
      {{- with $sm.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $sm.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
