{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "legacy-kafka.serviceAccountName" . }}
  namespace: {{ include "legacy-kafka.namespace" . }}
  labels:
    {{- include "legacy-kafka.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
