"""The two install bundles, rendered from the same boards the charts get.

A Helm chart is one way to deliver a board and it needs a cluster with these
charts in it. Two other shapes cover the people who have neither:

  provisioning/   a Grafana started with file provisioning and no sidecar —
                  `dashboards.yaml` names a provider and the JSON sits next to
                  it, which is the layout Grafana reads at boot.
  configmaps.yaml a cluster running the Grafana sidecar but not these charts —
                  one ConfigMap per board, carrying the label the sidecar
                  watches, in one `kubectl apply -f` file.

Both are GENERATED by scripts/gen-dashboards.py from the same
`dashboards/<board>/dashboard.json` the charts carry, and `--check` fails when
either has drifted. That is the whole point of generating them: a bundle that
is hand-maintained is a bundle that is a release behind, and a dashboard that
is a release behind reads as a dashboard that is broken.

Neither bundle is per-release, and neither has to be. Every board scopes itself
with `label_values(...)` dropdowns resolved from the data — including the
MirrorMaker 2 pair, whose namespace, cluster and pod regex were `constant`s a
release injected until the PodMonitor started carrying
`kafka-common.strimziRelabelings`. What a chart still writes into its own copy
is those variables' `current`, a preselection Grafana drops when the value is
not among the query's results; a bundled board simply opens on the first value
instead. The one exception is `kates-chaos-infra`, whose two hidden constants
(the execution plane's namespace and the Litmus operator Deployment) keep
LitmusChaos' own `litmus` default until a chart or a human sets them.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# What the bundles default to. All three are one edit away in the rendered
# file, and the ConfigMap bundle deliberately has no `metadata.namespace` at
# all so that `kubectl apply -n <ns>` decides it (an explicit namespace in the
# file makes `-n` an error rather than an override).
SIDECAR_LABEL = "grafana_dashboard"
SIDECAR_LABEL_VALUE = "1"
FOLDER = "Kates"

# Where the provider file expects to find the JSON once the bundle is mounted
# at Grafana's provisioning directory. One mount, not two: Grafana reads only
# *.yaml/*.yml for providers and does not recurse, so a subdirectory of JSON
# beside the provider file is inert to it and is exactly what `path` points at.
PROVISIONING_MOUNT = "/etc/grafana/provisioning/dashboards"
PROVISIONING_SUBDIR = "kates"

GENERATED_BY = "scripts/gen-dashboards.py"


def _warning(what: str) -> str:
    return (
        "# %s\n"
        "#\n"
        "# GENERATED by %s from dashboards/<board>/dashboard.json.\n"
        "# Do not edit: `%s --check` fails when this file has drifted, and\n"
        "# the next regeneration overwrites it. Edit the board's board.py.\n"
        % (what, GENERATED_BY, GENERATED_BY)
    )


def _block(text: str, indent: int) -> str:
    """`text` as the body of a YAML block scalar at `indent` spaces.

    Written out rather than handed to a YAML dumper because the bundles are
    compared byte for byte by `--check`: a dumper's line folding, quoting and
    key ordering are its own business and change between versions, and a
    135 KB dashboard is exactly the input that makes them change.
    """
    pad = " " * indent
    return "\n".join(pad + line if line else "" for line in text.splitlines())


# ── the provisioning bundle ─────────────────────────────────────────────────

def provisioning_provider(folder: str = FOLDER) -> str:
    """`provisioning/dashboards.yaml` — one file provider over the boards."""
    return _warning("Grafana dashboard provider for the Kates boards") + (
        "#\n"
        "# Mount the directory holding THIS file at %(mount)s\n"
        "# and Grafana loads every board in %(subdir)s/ at boot.\n"
        "#\n"
        "# `allowUiUpdates: false` is deliberate: these boards are generated, so\n"
        "# an edit in the UI is lost at the next restart either way. Saying so\n"
        "# here makes Grafana show the board as provisioned and refuse the save,\n"
        "# which is a better answer than accepting it and dropping it later.\n"
        "apiVersion: 1\n"
        "providers:\n"
        "  - name: kates\n"
        "    orgId: 1\n"
        "    folder: %(folder)s\n"
        "    type: file\n"
        "    disableDeletion: false\n"
        "    allowUiUpdates: false\n"
        "    updateIntervalSeconds: 30\n"
        "    options:\n"
        "      path: %(mount)s/%(subdir)s\n"
        "      foldersFromFilesStructure: false\n"
        % {"mount": PROVISIONING_MOUNT, "subdir": PROVISIONING_SUBDIR,
           "folder": folder}
    )


def provisioning_outputs(boards: list[tuple[str, dict[str, Any]]],
                         root: Path) -> list[tuple[Path, str]]:
    """Every file the provisioning bundle writes."""
    out = [(root / "provisioning" / "dashboards.yaml", provisioning_provider())]
    for name, board in boards:
        body = json.dumps(board, indent=2, sort_keys=True) + "\n"
        out.append((root / "provisioning" / PROVISIONING_SUBDIR / ("%s.json" % name),
                    body))
    return out


# ── the ConfigMap bundle ────────────────────────────────────────────────────

def configmap(name: str, board: dict[str, Any], *, label: str = SIDECAR_LABEL,
              label_value: str = SIDECAR_LABEL_VALUE,
              folder: str = FOLDER) -> str:
    """One board as a ConfigMap the Grafana sidecar will pick up.

    One ConfigMap per board rather than one for all twelve: together they are
    most of a megabyte, and a ConfigMap's ceiling is 1 MiB of etcd object —
    close enough that the next board is the one that breaks the apply. Per
    board also means a board can be deleted on its own.
    """
    body = json.dumps(board, indent=2, sort_keys=True)
    return (
        "apiVersion: v1\n"
        "kind: ConfigMap\n"
        "metadata:\n"
        "  # No namespace on purpose — `kubectl apply -n <ns>` picks it, and it\n"
        "  # has to be a namespace the sidecar searches (see README.md).\n"
        "  name: kates-dashboard-%(name)s\n"
        "  labels:\n"
        "    %(label)s: \"%(label_value)s\"\n"
        "    app.kubernetes.io/name: kates-dashboards\n"
        "    app.kubernetes.io/part-of: kates\n"
        "    app.kubernetes.io/managed-by: gen-dashboards.py\n"
        "  annotations:\n"
        "    grafana_folder: \"%(folder)s\"\n"
        "data:\n"
        "  %(name)s.json: |-\n"
        "%(body)s\n"
        % {"name": name, "label": label, "label_value": label_value,
           "folder": folder, "body": _block(body, 4)}
    )


def configmaps_bundle(boards: list[tuple[str, dict[str, Any]]]) -> str:
    """`configmaps.yaml` — every board, one `kubectl apply -f` away."""
    head = _warning("Every Kates Grafana board as a sidecar-labelled ConfigMap") + (
        "#\n"
        "#   kubectl apply -n <the namespace the sidecar searches> -f configmaps.yaml\n"
        "#\n"
        "# The sidecar watches for the label below (`%s: \"%s\"` is\n"
        "# kube-prometheus-stack's default) and files each board into the folder\n"
        "# named by the grafana_folder annotation, which needs\n"
        "# `sidecar.dashboards.folderAnnotation: grafana_folder` set on the\n"
        "# Grafana. Without it the boards still load, into the default folder.\n"
        % (SIDECAR_LABEL, SIDECAR_LABEL_VALUE)
    )
    docs = [configmap(name, board) for name, board in boards]
    return head + "---\n" + "---\n".join(docs)


# ── everything ──────────────────────────────────────────────────────────────

def outputs(boards: list[tuple[str, dict[str, Any]]],
            root: Path) -> list[tuple[Path, str]]:
    """Every (path, content) the bundles under `root` consist of."""
    return (provisioning_outputs(boards, root)
            + [(root / "configmaps.yaml", configmaps_bundle(boards))])
