{{- $secretName := printf "%s-auth" (include "kates-chaos.fullname" .) }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kates-chaos.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  admin-password: {{ .Values.auth.adminPassword | default "litmus" | b64enc | quote }}
  db-root-password: {{ .Values.auth.dbRootPassword | default (randAlphaNum 16) | b64enc | quote }}
  jwt-secret: {{ .Values.auth.jwtSecret | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
