{{- if and (not .Values.auth.existingSecret) .Values.auth.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kates-chaos.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kates-chaos.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKey | default "admin-password" }}: {{ .Values.auth.adminPassword | b64enc | quote }}
{{- end }}
