apiVersion: v2
appVersion: 3.3.0
description: A Helm chart for Kubernetes of Apicurio Registry, backed by the
  kafka-cluster chart (Strimzi) shipped in this repository
icon: https://design.jboss.org/apicurio/logo/logofiles/apicurio_icon_lightbkg_color.svg
name: apicurio-registry
type: application
version: 0.2.0
