# Velero Configuration
image:
  repository: docker.io/velero/velero
  tag: v1.17.1
  pullPolicy: IfNotPresent

initContainers:
  - name: velero-plugin-for-aws
    image: docker.io/velero/velero-plugin-for-aws:v1.10.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
  - name: default
    provider: aws
    bucket: velero
    config:
      region: minio
      s3ForcePathStyle: "true"
      s3Url: http://minio.velero.svc:9000
  volumeSnapshotLocation:
  - name: default
    provider: aws
    config:
      region: minio

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = minio
      aws_secret_access_key = minio123

snapshotsEnabled: false

deployNodeAgent: false

rbac:
  create: true
  clusterAdministrator: true

schedules:
  kafka-daily:
    disabled: false
    schedule: "0 0 * * *"
    template:
      includedNamespaces:
      - kafka
      - apicurio
      includedResources:
      - kafkatopics
      - kafkausers
      - kafkanodepools
      - kafkas
      - configmaps
      - secrets
      ttl: "720h"
