{{- if include "kafka-common.enabled" (list (.Values.autoscaling).enabled false) }}
{{- include "kafka-common.hpa" (dict
      "ctx" .
      "name" (include "connect-cluster.fullname" .)
      "namespace" (include "connect-cluster.namespace" .)
      "kind" "KafkaConnect"
      "labels" (include "connect-cluster.labels" .)
      "autoscaling" .Values.autoscaling
      "minDefault" 3
      "maxDefault" 10) }}
{{- end }}
