apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Injects network packet loss on target pods
kind: ChaosExperiment
metadata:
  name: pod-network-loss
  labels:
    name: pod-network-loss
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: 3.0.0
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create", "delete", "get", "list", "patch", "update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create", "get", "list", "patch", "update"]
      - apiGroups: [""]
        resources: ["pods/log", "pods/exec"]
        verbs: ["get", "list", "create"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create", "list", "get", "delete", "deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines", "chaosexperiments", "chaosresults"]
        verbs: ["create", "list", "get", "patch", "update", "delete"]
    image: litmuschaos/go-runner:3.25.0
    imagePullPolicy: IfNotPresent
    args:
      - -c
      - ./experiments -name pod-network-loss
    command:
      - /bin/bash
    env:
      - name: TOTAL_CHAOS_DURATION
        value: "60"
      - name: NETWORK_INTERFACE
        value: "eth0"
      - name: NETWORK_PACKET_LOSS_PERCENTAGE
        value: "100"
      - name: DESTINATION_IPS
        value: ""
      - name: DESTINATION_HOSTS
        value: ""
      - name: TARGET_CONTAINER
        value: ""
      - name: TARGET_PODS
        value: ""
      - name: PODS_AFFECTED_PERC
        value: ""
      - name: CONTAINER_RUNTIME
        value: "containerd"
      - name: SOCKET_PATH
        value: "/run/containerd/containerd.sock"
      - name: DEFAULT_HEALTH_CHECK
        value: "false"
      - name: SEQUENCE
        value: parallel
    labels:
      name: pod-network-loss
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: 3.0.0
