{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mirror-maker2.serviceAccountName" . }}
  namespace: {{ include "mirror-maker2.namespace" . }}
  labels:
    {{- include "mirror-maker2.labels" . | nindent 4 }}
{{- end }}
