package detect

import (
	"fmt"
	"io"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// RenderValues generates a YAML values file with the default 30% reserve.
func RenderValues(report *DetectReport, clusterName string, w io.Writer) error {
	return RenderValuesWithReserve(report, clusterName, 0.30, w)
}

// RenderValuesWithReserve generates a YAML values file with custom reserve.
func RenderValuesWithReserve(report *DetectReport, clusterName string, reserve float64, w io.Writer) error {
	gen := NewValuesGeneratorWithReserve(report, clusterName, reserve)
	vals := gen.Generate()

	// Write comment header
	zoneNames := make([]string, len(report.Zones))
	for i, z := range report.Zones {
		zoneNames[i] = z.Name
	}
	scNames := make([]string, len(report.Storage))
	for i, sc := range report.Storage {
		scNames[i] = sc.Name
	}

	totalCPU := 0
	totalMem := 0
	for _, n := range report.Nodes {
		totalCPU += n.CPU
		totalMem += n.MemoryGi
	}

	header := fmt.Sprintf(`# Auto-generated by kates detect --generate-values
# Provider: %s | Context: %s
# Date: %s
#
# ── Capacity Analysis ──
# Total cluster:    %d CPU, %d GiB
# Existing usage:   %dm CPU (%d%%), %d GiB
# Available:        %dm CPU, %d GiB
# Kafka budget:     %dm CPU (%d%%), %d GiB (%d%%)
# Reserve:          %d%%
# Weakest zone:     %s (%dm CPU, %dGi mem)
# Profile:          %s
#
# ── Component Distribution ──
# Controllers (×%d): %dm CPU, %s each
# Brokers (×%d):     %dm CPU, %s each
# Storage/broker:    %s
#
# ── Network & DNS ──
# CNI:              %s
# Cluster domain:   %s
# Local DNS suffix: svc.%s
# Pod CIDR:         %s
# Service CIDR:     %s
#
# Zones: %s
# StorageClasses: %s
# Strimzi: deployed=%v | Monitoring: prometheus=%v grafana=%v
# Kyverno=%v

`,
		report.Provider, report.Context,
		time.Now().UTC().Format(time.RFC3339),
		gen.Cap.TotalCPU/1000, gen.Cap.TotalMem,
		gen.Cap.UsedCPU, int(gen.Cap.UtilizationPct*100), gen.Cap.UsedMem,
		gen.Cap.AvailableCPU, gen.Cap.AvailableMem,
		gen.Cap.KafkaCPU, int((1.0-gen.Cap.ReservePct)*100),
		gen.Cap.KafkaMem, int((1.0-gen.Cap.ReservePct)*100),
		int(gen.Cap.ReservePct*100),
		gen.Cap.WeakestZone, gen.Cap.WeakestZoneCPU, gen.Cap.WeakestZoneMem,
		gen.Cap.Profile,
		gen.Cap.ControllerReplicas, gen.Cap.ControllerCPU, gen.Cap.ControllerStorage,
		gen.Cap.BrokerReplicas*max(len(report.Zones), 1), gen.Cap.BrokerCPU, formatMem(gen.Cap.BrokerMem),
		gen.Cap.BrokerStorage,
		report.Network.CNI,
		report.Network.ClusterDomain,
		report.Network.ClusterDomain,
		report.Network.PodCIDR,
		report.Network.ServiceCIDR,
		strings.Join(zoneNames, ", "),
		strings.Join(scNames, ", "),
		report.Strimzi.Running,
		report.Monitoring.PodMonitorCRD, report.Monitoring.GrafanaDeployed,
		report.Admission.Kyverno.Installed,
	)



	if _, err := fmt.Fprint(w, header); err != nil {
		return err
	}

	data, err := yaml.Marshal(vals)
	if err != nil {
		return fmt.Errorf("failed to marshal values: %w", err)
	}

	_, err = w.Write(data)
	return err
}

// RenderValuesFromBase merges detected values on top of a base values file.
func RenderValuesFromBase(report *DetectReport, clusterName string, baseData []byte, w io.Writer) error {
	return RenderValuesFromBaseWithReserve(report, clusterName, baseData, 0.30, w)
}

// RenderValuesFromBaseWithReserve merges detected values with custom reserve.
func RenderValuesFromBaseWithReserve(report *DetectReport, clusterName string, baseData []byte, reserve float64, w io.Writer) error {
	var base map[string]interface{}
	if err := yaml.Unmarshal(baseData, &base); err != nil {
		return fmt.Errorf("failed to parse base values: %w", err)
	}

	gen := NewValuesGeneratorWithReserve(report, clusterName, reserve)
	vals := gen.Generate()

	// Marshal generated values to map
	genData, err := yaml.Marshal(vals)
	if err != nil {
		return fmt.Errorf("failed to marshal generated values: %w", err)
	}
	var genMap map[string]interface{}
	if err := yaml.Unmarshal(genData, &genMap); err != nil {
		return fmt.Errorf("failed to unmarshal generated values: %w", err)
	}

	// Merge: detected values override base values
	merged := mergeMaps(base, genMap)

	// Write header
	header := fmt.Sprintf("# Auto-generated by kates detect --generate-values (merged with base)\n# Date: %s\n\n",
		time.Now().UTC().Format(time.RFC3339))
	if _, err := fmt.Fprint(w, header); err != nil {
		return err
	}

	data, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("failed to marshal merged values: %w", err)
	}
	_, err = w.Write(data)
	return err
}

// mergeMaps does a recursive deep merge of overlay on top of base.
// For overlapping keys:
// - If both are maps, they are merged recursively.
// - Otherwise, the overlay value overwrites the base value.
func mergeMaps(base, overlay map[string]interface{}) map[string]interface{} {
	result := make(map[string]interface{})
	for k, v := range base {
		result[k] = v
	}
	for k, v := range overlay {
		if vMap, ok := v.(map[string]interface{}); ok {
			if baseVal, exists := result[k]; exists {
				if bMap, okBase := baseVal.(map[string]interface{}); okBase {
					result[k] = mergeMaps(bMap, vMap)
					continue
				}
			}
		}
		result[k] = v
	}
	return result
}
