package detect

import (
	"fmt"
	"io"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// RenderValues generates a YAML values file from the DetectReport and writes it.
func RenderValues(report *DetectReport, clusterName string, w io.Writer) error {
	gen := NewValuesGenerator(report, clusterName)
	vals := gen.Generate()

	// Write comment header
	zoneNames := make([]string, len(report.Zones))
	for i, z := range report.Zones {
		zoneNames[i] = z.Name
	}
	scNames := make([]string, len(report.Storage))
	for i, sc := range report.Storage {
		scNames[i] = sc.Name
	}

	totalCPU := 0
	totalMem := 0
	for _, n := range report.Nodes {
		totalCPU += n.CPU
		totalMem += n.MemoryGi
	}

	header := fmt.Sprintf(`# Auto-generated by kates detect --generate-values
# Provider: %s | Context: %s
# Date: %s
# Profile: %s (%d CPU / %d GiB)
# Zones: %s
# StorageClasses: %s
# Strimzi: deployed=%v | Monitoring: prometheus=%v grafana=%v
# NetworkPolicy: CNI=%s | Kyverno=%v

`,
		report.Provider, report.Context,
		time.Now().UTC().Format(time.RFC3339),
		gen.Profile.Name, totalCPU/1000, totalMem,
		strings.Join(zoneNames, ", "),
		strings.Join(scNames, ", "),
		report.Strimzi.Running,
		report.Monitoring.PodMonitorCRD, report.Monitoring.GrafanaDeployed,
		report.Network.CNI, report.Admission.Kyverno.Installed,
	)

	if _, err := fmt.Fprint(w, header); err != nil {
		return err
	}

	data, err := yaml.Marshal(vals)
	if err != nil {
		return fmt.Errorf("failed to marshal values: %w", err)
	}

	_, err = w.Write(data)
	return err
}

// RenderValuesFromBase merges detected values on top of a base values file.
func RenderValuesFromBase(report *DetectReport, clusterName string, baseData []byte, w io.Writer) error {
	// Parse base values
	var base map[string]interface{}
	if err := yaml.Unmarshal(baseData, &base); err != nil {
		return fmt.Errorf("failed to parse base values: %w", err)
	}

	// Generate detected values
	gen := NewValuesGenerator(report, clusterName)
	vals := gen.Generate()

	// Marshal generated values to map
	genData, err := yaml.Marshal(vals)
	if err != nil {
		return fmt.Errorf("failed to marshal generated values: %w", err)
	}
	var genMap map[string]interface{}
	if err := yaml.Unmarshal(genData, &genMap); err != nil {
		return fmt.Errorf("failed to unmarshal generated values: %w", err)
	}

	// Merge: detected values override base values
	merged := mergeMaps(base, genMap)

	// Write header
	header := fmt.Sprintf("# Auto-generated by kates detect --generate-values (merged with base)\n# Date: %s\n\n",
		time.Now().UTC().Format(time.RFC3339))
	if _, err := fmt.Fprint(w, header); err != nil {
		return err
	}

	data, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("failed to marshal merged values: %w", err)
	}
	_, err = w.Write(data)
	return err
}

// mergeMaps does a shallow merge of overlay on top of base.
// For top-level keys that exist in overlay, the overlay value wins.
// Keys only in base are preserved.
func mergeMaps(base, overlay map[string]interface{}) map[string]interface{} {
	result := make(map[string]interface{})
	for k, v := range base {
		result[k] = v
	}
	for k, v := range overlay {
		result[k] = v
	}
	return result
}
