package detect

import (
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// RenderPDF compiles the complete compatibility report and exports it as a beautifully styled PDF document.
func RenderPDF(report *DetectReport, filePath string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 15)
	pdf.SetMargins(15, 15, 15)

	// Set running footer
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(0, 10, fmt.Sprintf("Page %d | Generated by kates detect", pdf.PageNo()), "", 0, "C", false, 0, "")
	})

	// Set running header
	pdf.SetHeaderFunc(func() {
		if pdf.PageNo() > 1 {
			pdf.SetFont("Helvetica", "B", 8)
			pdf.SetTextColor(100, 80, 200)
			pdf.CellFormat(0, 8, "Kates Compatibility Report", "B", 0, "L", false, 0, "")
			pdf.Ln(8)
		}
	})

	pdf.AddPage()

	// ── Title Hero Section ───────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 22)
	pdf.SetTextColor(100, 80, 200)
	pdf.CellFormat(0, 12, "Kafka Cluster Compatibility Report", "", 1, "L", false, 0, "")

	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5, fmt.Sprintf("Date: %s", time.Now().UTC().Format(time.RFC3339)), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 5, fmt.Sprintf("Context: %s  |  Provider: %s  |  K8s: %s  |  Helm: %s",
		report.Context, report.Provider, report.K8sVersion, report.HelmVersion), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	// ── Section Header Helper ────────────────────────────────────────────────
	sectionHeader := func(title string) {
		pdf.Ln(2)
		pdf.SetFont("Helvetica", "B", 12)
		pdf.SetTextColor(15, 23, 42)
		pdf.CellFormat(0, 8, title, "", 1, "L", false, 0, "")
		
		// Draw line under header
		pdf.SetDrawColor(100, 80, 200)
		pdf.SetLineWidth(0.4)
		x, y := pdf.GetX(), pdf.GetY()
		pdf.Line(x, y-1, x+180, y-1)
		pdf.Ln(2)
	}

	// ── Compatibility Verdict Card ───────────────────────────────────────────
	var bgR, bgG, bgB int
	var verdictText string
	var statusMsg string
	if report.Verdict.Fails == 0 && report.Verdict.Warns == 0 {
		bgR, bgG, bgB = 16, 185, 129 // green
		verdictText = "COMPATIBLE"
		statusMsg = "Cluster is fully compatible to run a production-ready 3-AZ Kafka deployment."
	} else if report.Verdict.Fails == 0 {
		bgR, bgG, bgB = 245, 158, 11 // amber
		verdictText = "COMPATIBLE WITH WARNINGS"
		statusMsg = fmt.Sprintf("Cluster is compatible but %d warning(s) were detected. Review remediation hints.", report.Verdict.Warns)
	} else {
		bgR, bgG, bgB = 239, 68, 68 // red
		verdictText = "INCOMPATIBLE"
		statusMsg = fmt.Sprintf("Cluster is incompatible. %d critical checks failed. Resolve issues before deploying.", report.Verdict.Fails)
	}

	pdf.SetFillColor(bgR, bgG, bgB)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(180, 10, verdictText, "1", 1, "C", true, 0, "")
	pdf.Ln(1)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(180, 6, statusMsg, "", 1, "L", false, 0, "")
	pdf.Ln(4)

	// ── Nodes Table ──────────────────────────────────────────────────────────
	if len(report.Nodes) > 0 {
		sectionHeader(fmt.Sprintf("Nodes (%d total)", len(report.Nodes)))
		
		colWidths := []float64{50, 30, 30, 20, 20, 30}
		headers := []string{"Name", "Zone", "Roles", "CPU", "Memory", "Kubelet"}
		
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(30, 41, 59)
		pdf.SetTextColor(196, 181, 253)
		for i, h := range headers {
			pdf.CellFormat(colWidths[i], 6, h, "1", 0, "L", true, 0, "")
		}
		pdf.Ln(-1)

		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(60, 60, 60)
		for idx, n := range report.Nodes {
			if idx%2 == 0 {
				pdf.SetFillColor(248, 250, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			pdf.CellFormat(colWidths[0], 6, n.Name, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[1], 6, n.Zone, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[2], 6, n.Roles, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[3], 6, fmt.Sprintf("%dm", n.CPU), "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[4], 6, fmt.Sprintf("%dGi", n.MemoryGi), "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[5], 6, n.Kubelet, "1", 0, "L", true, 0, "")
			pdf.Ln(-1)
		}
		pdf.Ln(4)
	}

	// ── Zones Table ──────────────────────────────────────────────────────────
	if len(report.Zones) > 0 {
		sectionHeader(fmt.Sprintf("Zones (%d total)", len(report.Zones)))
		
		colWidths := []float64{50, 30, 50, 50}
		headers := []string{"Zone", "Nodes", "CPU", "Memory"}
		
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(30, 41, 59)
		pdf.SetTextColor(196, 181, 253)
		for i, h := range headers {
			pdf.CellFormat(colWidths[i], 6, h, "1", 0, "L", true, 0, "")
		}
		pdf.Ln(-1)

		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(60, 60, 60)
		for idx, z := range report.Zones {
			if idx%2 == 0 {
				pdf.SetFillColor(248, 250, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			pdf.CellFormat(colWidths[0], 6, z.Name, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[1], 6, strconv.Itoa(z.Nodes), "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[2], 6, fmt.Sprintf("%dm", z.CPUAllocatable), "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[3], 6, fmt.Sprintf("%dGi", z.MemAllocatableGi), "1", 0, "L", true, 0, "")
			pdf.Ln(-1)
		}
		pdf.Ln(4)
	}

	// ── Storage Classes Table ────────────────────────────────────────────────
	if len(report.Storage) > 0 {
		sectionHeader("StorageClasses")
		
		hasBenchResults := false
		for _, sc := range report.Storage {
			if sc.ProbedIOPS > 0 || sc.ProbeLatencyMs > 0 {
				hasBenchResults = true
				break
			}
		}

		var colWidths []float64
		var headers []string
		if hasBenchResults {
			colWidths = []float64{25, 40, 30, 15, 10, 10, 25, 25}
			headers = []string{"Name", "Provisioner", "Binding Mode", "Reclaim", "Def", "Exp", "Probed IOPS", "Latency"}
		} else {
			colWidths = []float64{35, 60, 35, 20, 15, 15}
			headers = []string{"Name", "Provisioner", "Binding Mode", "Reclaim", "Def", "Exp"}
		}
		
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(30, 41, 59)
		pdf.SetTextColor(196, 181, 253)
		for i, h := range headers {
			pdf.CellFormat(colWidths[i], 6, h, "1", 0, "L", true, 0, "")
		}
		pdf.Ln(-1)

		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(60, 60, 60)
		for idx, sc := range report.Storage {
			if idx%2 == 0 {
				pdf.SetFillColor(248, 250, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			defVal := "no"
			if sc.IsDefault {
				defVal = "yes"
			}
			expVal := "no"
			if sc.AllowExpansion {
				expVal = "yes"
			}
			
			if hasBenchResults {
				iopsVal := "—"
				if sc.ProbedIOPS > 0 {
					iopsVal = strconv.Itoa(sc.ProbedIOPS)
				}
				latVal := "—"
				if sc.ProbeLatencyMs > 0 {
					latVal = fmt.Sprintf("%.2fms", sc.ProbeLatencyMs)
				}
				pdf.CellFormat(colWidths[0], 6, sc.Name, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[1], 6, sc.Provisioner, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[2], 6, sc.BindingMode, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[3], 6, sc.ReclaimPolicy, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[4], 6, defVal, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[5], 6, expVal, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[6], 6, iopsVal, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[7], 6, latVal, "1", 0, "L", true, 0, "")
			} else {
				pdf.CellFormat(colWidths[0], 6, sc.Name, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[1], 6, sc.Provisioner, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[2], 6, sc.BindingMode, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[3], 6, sc.ReclaimPolicy, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[4], 6, defVal, "1", 0, "L", true, 0, "")
				pdf.CellFormat(colWidths[5], 6, expVal, "1", 0, "L", true, 0, "")
			}
			pdf.Ln(-1)
		}
		
		if report.StorageAudit.PVCount > 0 {
			pdf.Ln(2)
			pdf.SetFont("Helvetica", "", 9)
			pdf.CellFormat(0, 5, fmt.Sprintf("PV Inventory: %d total (%d bound, %s capacity)",
				report.StorageAudit.PVCount, report.StorageAudit.PVBoundCount, report.StorageAudit.PVTotalCapacity), "", 1, "L", false, 0, "")
		}
		if len(report.StorageAudit.CSIDrivers) > 0 {
			pdf.CellFormat(0, 5, fmt.Sprintf("CSIDrivers: %s", strings.Join(report.StorageAudit.CSIDrivers, ", ")), "", 1, "L", false, 0, "")
		}
		pdf.Ln(4)
	}

	// ── Strimzi Operator Health ──────────────────────────────────────────────
	sectionHeader("Strimzi Operator")
	pdf.SetFont("Helvetica", "", 9)
	if report.Strimzi.Running {
		pdf.CellFormat(0, 5, fmt.Sprintf("- Status: Running in namespace '%s' (Health: %s)", report.Strimzi.Namespace, report.Strimzi.Health.Status), "", 1, "L", false, 0, "")
		pdf.CellFormat(0, 5, fmt.Sprintf("- Image: %s", report.Strimzi.Image), "", 1, "L", false, 0, "")
		pdf.CellFormat(0, 5, fmt.Sprintf("- Replicas: %d/%d ready", report.Strimzi.ReadyReplicas, report.Strimzi.TotalReplicas), "", 1, "L", false, 0, "")
		
		if len(report.Strimzi.Health.WarningLogs) > 0 {
			pdf.Ln(1)
			pdf.SetFont("Helvetica", "B", 8)
			pdf.CellFormat(0, 4, "Logged operator warning snippets:", "", 1, "L", false, 0, "")
			pdf.SetFont("Courier", "", 7.5)
			pdf.SetTextColor(120, 40, 40)
			for _, logLine := range report.Strimzi.Health.WarningLogs {
				if len(logLine) > 105 {
					logLine = logLine[:102] + "..."
				}
				pdf.CellFormat(0, 4, logLine, "", 1, "L", false, 0, "")
			}
			pdf.SetTextColor(60, 60, 60)
			pdf.SetFont("Helvetica", "", 9)
		}
	} else if report.Strimzi.CRDsPresent {
		pdf.CellFormat(0, 5, "- Status: CRDs present, but operator deployment NOT found", "", 1, "L", false, 0, "")
	} else {
		pdf.CellFormat(0, 5, "- Status: Operator NOT installed", "", 1, "L", false, 0, "")
	}
	if len(report.Strimzi.Health.MissingCRDs) > 0 {
		pdf.CellFormat(0, 5, fmt.Sprintf("- Missing CRDs: %s", strings.Join(report.Strimzi.Health.MissingCRDs, ", ")), "", 1, "L", false, 0, "")
	}
	if report.Strimzi.CapacityStatus != "" {
		pdf.CellFormat(0, 5, fmt.Sprintf("- Kafka Capacity: %s", report.Strimzi.CapacityStatus), "", 1, "L", false, 0, "")
	}
	pdf.Ln(4)

	// ── Active Zone Network Latency Matrix ───────────────────────────────────
	if len(report.Network.LatencyMatrix) > 0 {
		sectionHeader("Active Zone Network Latency Matrix")
		
		// extract unique zones
		zoneMap := make(map[string]bool)
		for _, r := range report.Network.LatencyMatrix {
			zoneMap[r.SourceZone] = true
			zoneMap[r.TargetZone] = true
		}
		var zones []string
		for z := range zoneMap {
			zones = append(zones, z)
		}
		
		colWidth := 135.0 / float64(len(zones))
		
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(30, 41, 59)
		pdf.SetTextColor(196, 181, 253)
		pdf.CellFormat(45, 6, "Source \\ Target", "1", 0, "C", true, 0, "")
		for _, z := range zones {
			pdf.CellFormat(colWidth, 6, z, "1", 0, "C", true, 0, "")
		}
		pdf.Ln(-1)
		
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(60, 60, 60)
		for i, src := range zones {
			if i%2 == 0 {
				pdf.SetFillColor(248, 250, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			pdf.SetFont("Helvetica", "B", 8)
			pdf.CellFormat(45, 6, src, "1", 0, "C", true, 0, "")
			pdf.SetFont("Helvetica", "", 8)
			
			for _, dst := range zones {
				found := false
				for _, r := range report.Network.LatencyMatrix {
					if r.SourceZone == src && r.TargetZone == dst {
						if r.Success {
							pdf.CellFormat(colWidth, 6, fmt.Sprintf("%.2fms", r.AvgMs), "1", 0, "C", true, 0, "")
						} else {
							pdf.SetTextColor(239, 68, 68)
							pdf.CellFormat(colWidth, 6, "FAIL", "1", 0, "C", true, 0, "")
							pdf.SetTextColor(60, 60, 60)
						}
						found = true
						break
					}
				}
				if !found {
					pdf.CellFormat(colWidth, 6, "—", "1", 0, "C", true, 0, "")
				}
			}
			pdf.Ln(-1)
		}
		pdf.Ln(4)
	}

	// ── Active Zone Network Bandwidth Matrix ─────────────────────────────────
	if len(report.Network.BandwidthMatrix) > 0 {
		sectionHeader("Active Zone Network Bandwidth Matrix")
		
		// extract unique zones
		zoneMap := make(map[string]bool)
		for _, r := range report.Network.BandwidthMatrix {
			zoneMap[r.SourceZone] = true
			zoneMap[r.TargetZone] = true
		}
		var zones []string
		for z := range zoneMap {
			zones = append(zones, z)
		}
		
		colWidth := 135.0 / float64(len(zones))
		
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(30, 41, 59)
		pdf.SetTextColor(196, 181, 253)
		pdf.CellFormat(45, 6, "Source \\ Target", "1", 0, "C", true, 0, "")
		for _, z := range zones {
			pdf.CellFormat(colWidth, 6, z, "1", 0, "C", true, 0, "")
		}
		pdf.Ln(-1)
		
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(60, 60, 60)
		for i, src := range zones {
			if i%2 == 0 {
				pdf.SetFillColor(248, 250, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			pdf.SetFont("Helvetica", "B", 8)
			pdf.CellFormat(45, 6, src, "1", 0, "C", true, 0, "")
			pdf.SetFont("Helvetica", "", 8)
			
			for _, dst := range zones {
				if src == dst {
					pdf.CellFormat(colWidth, 6, "—", "1", 0, "C", true, 0, "")
					continue
				}
				found := false
				for _, r := range report.Network.BandwidthMatrix {
					if r.SourceZone == src && r.TargetZone == dst {
						if r.Success {
							pdf.CellFormat(colWidth, 6, fmt.Sprintf("%.1f Mbps", r.BandwidthMbps), "1", 0, "C", true, 0, "")
						} else {
							pdf.SetTextColor(239, 68, 68)
							pdf.CellFormat(colWidth, 6, "FAIL", "1", 0, "C", true, 0, "")
							pdf.SetTextColor(60, 60, 60)
						}
						found = true
						break
					}
				}
				if !found {
					pdf.CellFormat(colWidth, 6, "—", "1", 0, "C", true, 0, "")
				}
			}
			pdf.Ln(-1)
		}
		pdf.Ln(4)
	}

	// ── Active CoreDNS Latency & Success Audits ──────────────────────────────
	if len(report.Network.DNSResults) > 0 {
		sectionHeader("Active CoreDNS Latency & Success Audits")
		
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(30, 41, 59)
		pdf.SetTextColor(196, 181, 253)
		
		pdf.CellFormat(40, 6, "Query Type", "1", 0, "C", true, 0, "")
		pdf.CellFormat(25, 6, "Queries Run", "1", 0, "C", true, 0, "")
		pdf.CellFormat(25, 6, "Success Count", "1", 0, "C", true, 0, "")
		pdf.CellFormat(30, 6, "Success Rate", "1", 0, "C", true, 0, "")
		pdf.CellFormat(30, 6, "Avg Latency", "1", 0, "C", true, 0, "")
		pdf.CellFormat(30, 6, "Max Latency", "1", 0, "C", true, 0, "")
		pdf.Ln(-1)
		
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(60, 60, 60)
		for i, r := range report.Network.DNSResults {
			if i%2 == 0 {
				pdf.SetFillColor(248, 250, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			pdf.CellFormat(40, 6, r.QueryType, "1", 0, "C", true, 0, "")
			pdf.CellFormat(25, 6, fmt.Sprintf("%d", r.QueriesRun), "1", 0, "C", true, 0, "")
			pdf.CellFormat(25, 6, fmt.Sprintf("%d", r.SuccessCount), "1", 0, "C", true, 0, "")
			pdf.CellFormat(30, 6, fmt.Sprintf("%.1f%%", r.SuccessRate), "1", 0, "C", true, 0, "")
			pdf.CellFormat(30, 6, fmt.Sprintf("%.2fms", r.AvgLatencyMs), "1", 0, "C", true, 0, "")
			pdf.CellFormat(30, 6, fmt.Sprintf("%.2fms", r.MaxLatencyMs), "1", 0, "C", true, 0, "")
			pdf.Ln(-1)
		}
		pdf.Ln(4)
	}

	// ── Admission Controllers & Secret Audits ────────────────────────────────
	sectionHeader("Admission Controllers & Security Audit")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(0, 5, fmt.Sprintf("- Pod Security Admission (PSA) Label: %s", report.Security.PSALabelEnforced), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 5, fmt.Sprintf("- Kyverno Enforced: %t", report.Security.KyvernoEnforced), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 5, fmt.Sprintf("- Namespace Management Permissions: %t", report.Security.PermissionsOk), "", 1, "L", false, 0, "")
	if report.Admission.Kyverno.Installed {
		pdf.CellFormat(0, 5, fmt.Sprintf("- Kyverno: Running in '%s' (v%s) with %d policies (%d Kafka-relevant)",
			report.Admission.Kyverno.Namespace, report.Admission.Kyverno.Version,
			len(report.Admission.Kyverno.ClusterPolicies), len(report.Admission.Kyverno.KafkaRelevant)), "", 1, "L", false, 0, "")
	} else {
		pdf.CellFormat(0, 5, "- Kyverno: Not installed", "", 1, "L", false, 0, "")
	}
	if report.Admission.Gatekeeper.Installed {
		pdf.CellFormat(0, 5, fmt.Sprintf("- OPA Gatekeeper: Running in '%s' (%d constraints)",
			report.Admission.Gatekeeper.Namespace, len(report.Admission.Gatekeeper.Constraints)), "", 1, "L", false, 0, "")
	} else {
		pdf.CellFormat(0, 5, "- OPA Gatekeeper: Not installed", "", 1, "L", false, 0, "")
	}

	// Secrets Audit Status
	if report.SecretAudit.NamespaceCreated {
		if report.SecretAudit.SecretCreated {
			pdf.CellFormat(0, 5, "- Secrets Provisioning: verified (functional in temporary namespace)", "", 1, "L", false, 0, "")
		} else {
			if report.SecretAudit.BlockedByPolicy {
				pdf.SetTextColor(239, 68, 68)
				pdf.CellFormat(0, 5, fmt.Sprintf("- Secrets Provisioning: BLOCKED by Admission Policy '%s'", report.SecretAudit.PolicyName), "", 1, "L", false, 0, "")
				pdf.SetTextColor(60, 60, 60)
			} else {
				pdf.SetTextColor(239, 68, 68)
				pdf.CellFormat(0, 5, fmt.Sprintf("- Secrets Provisioning: FAILED with error: %s", report.SecretAudit.ErrorMsg), "", 1, "L", false, 0, "")
				pdf.SetTextColor(60, 60, 60)
			}
		}
	} else if report.SecretAudit.ErrorMsg != "" {
		pdf.CellFormat(0, 5, fmt.Sprintf("- Secrets Provisioning: failed namespace setup (%s)", report.SecretAudit.ErrorMsg), "", 1, "L", false, 0, "")
	} else {
		pdf.CellFormat(0, 5, "- Secrets Provisioning: Not audited", "", 1, "L", false, 0, "")
	}
	pdf.Ln(4)

	// ── NetworkPolicies Table ────────────────────────────────────────────────
	if report.NetPolAudit.TotalCount > 0 {
		sectionHeader("NetworkPolicies (kafka namespace)")
		
		colWidths := []float64{50, 65, 25, 20, 20}
		headers := []string{"Name", "Pod Selector", "Policy Types", "In/Out Rules", "Managed By"}
		
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(30, 41, 59)
		pdf.SetTextColor(196, 181, 253)
		for i, h := range headers {
			pdf.CellFormat(colWidths[i], 6, h, "1", 0, "L", true, 0, "")
		}
		pdf.Ln(-1)

		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(60, 60, 60)
		for idx, np := range report.NetPolAudit.Existing {
			if idx%2 == 0 {
				pdf.SetFillColor(248, 250, 252)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			types := strings.Join(np.PolicyTypes, ",")
			rulesStr := fmt.Sprintf("%d/%d", np.IngressRules, np.EgressRules)
			
			selector := np.PodSelector
			if len(selector) > 42 {
				selector = selector[:39] + "..."
			}
			
			pdf.CellFormat(colWidths[0], 6, np.Name, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[1], 6, selector, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[2], 6, types, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[3], 6, rulesStr, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colWidths[4], 6, np.ManagedBy, "1", 0, "L", true, 0, "")
			pdf.Ln(-1)
		}
		pdf.Ln(4)
	}

	// ── Resource Budget ──────────────────────────────────────────────────────
	sectionHeader("Resource Budget & Requirements")
	
	colWidths := []float64{60, 60, 60}
	headers := []string{"Component", "CPU", "Memory"}
	
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(196, 181, 253)
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 6, h, "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(60, 60, 60)
	
	pdf.SetFillColor(248, 250, 252)
	pdf.CellFormat(colWidths[0], 6, "Controllers", "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[1], 6, fmt.Sprintf("%dm", report.Budget.CtrlCPU), "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[2], 6, fmt.Sprintf("%dGi", report.Budget.CtrlMem), "1", 0, "L", true, 0, "")
	pdf.Ln(-1)

	pdf.SetFillColor(255, 255, 255)
	pdf.CellFormat(colWidths[0], 6, "Brokers (x3 zones)", "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[1], 6, fmt.Sprintf("%dm", report.Budget.BrokerCPU*3), "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[2], 6, fmt.Sprintf("%dGi", report.Budget.BrokerMem*3), "1", 0, "L", true, 0, "")
	pdf.Ln(-1)

	pdf.SetFillColor(248, 250, 252)
	pdf.CellFormat(colWidths[0], 6, "Operators + Exporter", "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[1], 6, fmt.Sprintf("%dm", report.Budget.OtherCPU), "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[2], 6, fmt.Sprintf("%dGi", report.Budget.OtherMem), "1", 0, "L", true, 0, "")
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetFillColor(230, 230, 250)
	pdf.CellFormat(colWidths[0], 6, "TOTAL REQUIRED", "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[1], 6, fmt.Sprintf("%dm", report.Budget.NeedCPU), "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[2], 6, fmt.Sprintf("%dGi", report.Budget.NeedMem), "1", 0, "L", true, 0, "")
	pdf.Ln(-1)

	pdf.SetFillColor(240, 248, 255)
	pdf.CellFormat(colWidths[0], 6, "CLUSTER AVAILABLE", "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[1], 6, fmt.Sprintf("%dm", report.Budget.TotalCPU), "1", 0, "L", true, 0, "")
	pdf.CellFormat(colWidths[2], 6, fmt.Sprintf("%dGi", report.Budget.TotalMem), "1", 0, "L", true, 0, "")
	pdf.Ln(-1)
	
	pdf.Ln(2)
	sufficientText := "Sufficient resources available"
	if !report.Budget.Sufficient {
		sufficientText = "Insufficient resources available"
		pdf.SetTextColor(239, 68, 68)
	} else {
		pdf.SetTextColor(16, 185, 129)
	}
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(0, 6, "Status: "+sufficientText, "", 1, "L", false, 0, "")
	pdf.Ln(2)
	pdf.SetTextColor(60, 60, 60)

	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(0, 6, "Sizing Profile Recommendation", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.CellFormat(0, 5, fmt.Sprintf("- Recommended Sizing Profile: %s", strings.ToUpper(report.Budget.RecommendedProfile)), "", 1, "L", false, 0, "")
	
	desc := ""
	switch report.Budget.RecommendedProfile {
	case "production":
		desc = "Resilient, highly available production workload capacity (spans 3 AZs)."
	case "standard":
		desc = "Standard capacity, suitable for staging/moderate production."
	case "minimal":
		desc = "Minimal capacity, suitable for dev, test, or lightweight sandboxes."
	default:
		desc = "Scale cluster capacity to meet at least Minimal sizing requirements."
	}
	pdf.CellFormat(0, 5, fmt.Sprintf("- Description: %s", desc), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	// ── Compatibility Verdict Checks Table ───────────────────────────────────
	sectionHeader("Compatibility Verdict Checks")
	
	colWidths = []float64{65, 25, 90}
	headers = []string{"Check", "Status", "Details"}
	
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(196, 181, 253)
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 6, h, "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(60, 60, 60)
	for idx, c := range report.Verdict.Checks {
		if idx%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		
		statusStr := "PASS"
		if !c.Status {
			statusStr = "FAIL"
			pdf.SetTextColor(239, 68, 68)
		} else {
			pdf.SetTextColor(16, 185, 129)
		}
		
		pdf.CellFormat(colWidths[0], 6, c.Description, "1", 0, "L", true, 0, "")
		pdf.CellFormat(colWidths[1], 6, statusStr, "1", 0, "L", true, 0, "")
		
		pdf.SetTextColor(60, 60, 60)
		detailText := c.Detail
		if len(detailText) > 55 {
			detailText = detailText[:52] + "..."
		}
		pdf.CellFormat(colWidths[2], 6, detailText, "1", 0, "L", true, 0, "")
		pdf.Ln(-1)
	}
	pdf.Ln(4)

	// ── Remediation Hints ────────────────────────────────────────────────────
	hints := GenerateRemediation(report)
	if len(hints) > 0 {
		sectionHeader("Remediation Hints")
		
		for _, h := range hints {
			// Title of hint
			pdf.SetFont("Helvetica", "B", 9)
			if h.Severity == "critical" {
				pdf.SetTextColor(239, 68, 68) // red
				pdf.CellFormat(0, 5, "CRITICAL: "+h.Summary, "", 1, "L", false, 0, "")
			} else if h.Severity == "warning" {
				pdf.SetTextColor(245, 158, 11) // amber
				pdf.CellFormat(0, 5, "WARNING: "+h.Summary, "", 1, "L", false, 0, "")
			} else {
				pdf.SetTextColor(100, 80, 200) // indigo
				pdf.CellFormat(0, 5, "INFO: "+h.Summary, "", 1, "L", false, 0, "")
			}
			
			pdf.SetTextColor(60, 60, 60)
			pdf.SetFont("Helvetica", "", 8.5)
			
			// Command details
			if len(h.Commands) > 0 {
				pdf.Ln(1)
				pdf.SetFont("Courier", "", 8)
				pdf.SetFillColor(240, 240, 240)
				for _, cmd := range h.Commands {
					if len(cmd) > 95 {
						cmd = cmd[:92] + "..."
					}
					pdf.CellFormat(180, 5.5, "  "+cmd, "1", 1, "L", true, 0, "")
				}
				pdf.SetFont("Helvetica", "", 8.5)
				pdf.Ln(1)
			}
			
			if h.DocURL != "" {
				pdf.SetTextColor(100, 80, 200)
				pdf.CellFormat(0, 4, "Documentation: "+h.DocURL, "", 1, "L", false, 0, h.DocURL)
				pdf.SetTextColor(60, 60, 60)
			}
			pdf.Ln(2)
		}
	}

	return pdf.OutputFileAndClose(filePath)
}
