{{- if .Values.networkPolicies.enabled }}
{{- $clusterName := include "kafka-cluster.clusterName" . -}}
{{- $namespace := include "kafka-cluster.namespace" . -}}
{{- $monitoringNs := .Values.networkPolicies.monitoringNamespace -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to: []
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-brokers
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/kind: Kafka
      strimzi.io/cluster: {{ $clusterName }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ $clusterName }}
      ports:
        - port: 9091
          protocol: TCP
    - from:
        {{- range .Values.networkPolicies.allowedClientNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
        - podSelector:
            matchLabels:
              app: kafka-ui
        - podSelector:
            matchLabels:
              app: apicurio-registry
      ports:
        - port: 9092
          protocol: TCP
    - from:
        {{- range .Values.networkPolicies.allowedClientNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
      ports:
        - port: 9093
          protocol: TCP
    - from: []
      ports:
        - port: 9094
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $monitoringNs }}
      ports:
        - port: 9404
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ $clusterName }}
    - to: []
      ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-controllers
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/pool-name: controllers
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ $clusterName }}
      ports:
        - port: 9090
          protocol: TCP
        - port: 9091
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ $clusterName }}
    - to: []
      ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: strimzi-operator
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $monitoringNs }}
      ports:
        - port: 8080
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ $clusterName }}
    - to: []
      ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-ui
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: kafka-ui
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - port: 8080
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/kind: Kafka
      ports:
        - port: 9092
          protocol: TCP
    - to: []
      ports:
        - port: 443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cruise-control
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/kind: Kafka
      strimzi.io/name: {{ $clusterName }}-cruise-control
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              strimzi.io/kind: cluster-operator
      ports:
        - port: 9090
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $monitoringNs }}
      ports:
        - port: 9404
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ $clusterName }}
    - to: []
      ports:
        - port: 443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: strimzi-drain-cleaner
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: strimzi-drain-cleaner
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - port: 8443
          protocol: TCP
  egress:
    - to: []
      ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-connect
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: kates-connect
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $monitoringNs }}
      ports:
        - port: 9404
          protocol: TCP
    - from:
        {{- range .Values.networkPolicies.allowedClientNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
      ports:
        - port: 8083
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/kind: Kafka
      ports:
        - port: 9092
          protocol: TCP
    - to: []
      ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-mirror-maker
  namespace: {{ $namespace }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/kind: KafkaMirrorMaker2
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $monitoringNs }}
      ports:
        - port: 9404
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              strimzi.io/kind: Kafka
      ports:
        - port: 9092
          protocol: TCP
    - to: []
      ports:
        - port: 9092
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
{{- end }}
