{{- if .Values.podMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-operator-metrics
  namespace: {{ include "kafka-cluster.namespace" . }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
    {{- with .Values.podMonitors.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - {{ include "kafka-cluster.namespace" . }}
  podMetricsEndpoints:
  - path: /metrics
    port: http
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-resources-metrics
  namespace: {{ include "kafka-cluster.namespace" . }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
    {{- with .Values.podMonitors.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchExpressions:
      - key: "strimzi.io/kind"
        operator: In
        values: ["Kafka", "KafkaConnect", "KafkaMirrorMaker", "KafkaMirrorMaker2"]
  namespaceSelector:
    matchNames:
      - {{ include "kafka-cluster.namespace" . }}
  podMetricsEndpoints:
  - path: /metrics
    port: tcp-prometheus
    relabelings:
    - separator: ;
      regex: __meta_kubernetes_pod_label_(.+)
      replacement: $1
      action: labelmap
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: kubernetes_pod_name
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      action: replace
      targetLabel: kubernetes_node_name
{{- end }}
