{{- if and .Values.kafkaConnect.enabled .Values.podMonitors.enabled }}
{{- $clusterName := include "kafka-cluster.clusterName" . -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $clusterName }}-connect
  namespace: {{ include "kafka-cluster.namespace" . }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
    {{- with .Values.podMonitors.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      strimzi.io/name: {{ $clusterName }}-connect
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
{{- end }}
