package cmd

import (
	"strings"
	"testing"

	"github.com/klster/kates-cli/client"
)

func TestRenderMarkdownReport_Basic(t *testing.T) {
	report := &client.Report{
		Summary: &client.ReportSummary{
			TotalRecords:            100000,
			AvgThroughputRecPerSec:  50000,
			PeakThroughputRecPerSec: 75000,
			AvgThroughputMBPerSec:   48.8,
			AvgLatencyMs:            5.2,
			P50LatencyMs:            4.1,
			P95LatencyMs:            12.3,
			P99LatencyMs:            25.7,
			MaxLatencyMs:            120.0,
			ErrorRate:               0.0001,
		},
	}

	md := renderMarkdownReport("test-123", report)

	expectations := []string{
		"# Kates Performance Report",
		"**Test ID**: `test-123`",
		"## Throughput",
		"100.0K",
		"## Latency Distribution",
		"P99",
		"25.70",
		"## Reliability",
		"0.0100%",
	}
	for _, exp := range expectations {
		if !strings.Contains(md, exp) {
			t.Errorf("markdown report missing: %s", exp)
		}
	}
}

func TestRenderMarkdownReport_WithSLA(t *testing.T) {
	report := &client.Report{
		Summary: &client.ReportSummary{TotalRecords: 1000},
		OverallSlaVerdict: &client.SlaVerdict{
			Passed: false,
			Violations: []client.SlaViolation{
				{Metric: "p99LatencyMs", Threshold: 50, Actual: 120},
			},
		},
	}

	md := renderMarkdownReport("sla-test", report)

	if !strings.Contains(md, "SLA violations detected") {
		t.Error("expected SLA violations text")
	}
	if !strings.Contains(md, "p99LatencyMs") {
		t.Error("expected violation metric name")
	}
}

func TestRenderMarkdownReport_SLAPassed(t *testing.T) {
	report := &client.Report{
		Summary: &client.ReportSummary{TotalRecords: 1000},
		OverallSlaVerdict: &client.SlaVerdict{
			Passed: true,
		},
	}

	md := renderMarkdownReport("pass-test", report)

	if !strings.Contains(md, "All SLA thresholds met") {
		t.Error("expected SLA pass text")
	}
}

func TestRenderMarkdownReport_WithPhases(t *testing.T) {
	report := &client.Report{
		Summary: &client.ReportSummary{TotalRecords: 1000},
		Phases: []client.ReportPhase{
			{Name: "warmup", Status: "DONE", RecordsSent: 500, ThroughputRecPerSec: 10000, P99LatencyMs: 15.5, ErrorRate: 0},
			{Name: "main", Status: "DONE", RecordsSent: 500, ThroughputRecPerSec: 25000, P99LatencyMs: 22.3, ErrorRate: 0.001},
		},
	}

	md := renderMarkdownReport("phase-test", report)

	if !strings.Contains(md, "## Phase Breakdown") {
		t.Error("expected Phase Breakdown section")
	}
	if !strings.Contains(md, "warmup") {
		t.Error("expected warmup phase")
	}
	if !strings.Contains(md, "main") {
		t.Error("expected main phase")
	}
}

func TestRenderMarkdownReport_NilSummary(t *testing.T) {
	report := &client.Report{}
	md := renderMarkdownReport("nil-test", report)
	if !strings.Contains(md, "# Kates Performance Report") {
		t.Error("report should still have header")
	}
}

func TestRenderMarkdownReport_Footer(t *testing.T) {
	report := &client.Report{Summary: &client.ReportSummary{TotalRecords: 1}}
	md := renderMarkdownReport("footer-test", report)
	if !strings.Contains(md, "Generated by") {
		t.Error("expected footer")
	}
	if !strings.Contains(md, "footer-test") {
		t.Error("expected test ID in footer")
	}
}
