package cmd

import (
	"fmt"
	"strings"

	"github.com/klster/kates-cli/client"
)

func renderMarkdownReport(id string, r *client.Report) string {
	var b strings.Builder

	b.WriteString("# Kates Performance Report\n\n")
	b.WriteString(fmt.Sprintf("**Test ID**: `%s`\n\n", id))

	if s := r.Summary; s != nil {
		b.WriteString("## Throughput\n\n")
		b.WriteString("| Metric | Value |\n|---|---|\n")
		b.WriteString(fmt.Sprintf("| Total Records | %s |\n", fmtNum(s.TotalRecords)))
		b.WriteString(fmt.Sprintf("| Avg Throughput | %s rec/s |\n", fmtNum(s.AvgThroughputRecPerSec)))
		b.WriteString(fmt.Sprintf("| Peak Throughput | %s rec/s |\n", fmtNum(s.PeakThroughputRecPerSec)))
		b.WriteString(fmt.Sprintf("| Avg MB/s | %s |\n", fmtFloat(s.AvgThroughputMBPerSec, 2)))

		b.WriteString("\n## Latency Distribution\n\n")
		b.WriteString("| Percentile | Value (ms) |\n|---|---|\n")
		b.WriteString(fmt.Sprintf("| Average | %.2f |\n", s.AvgLatencyMs))
		b.WriteString(fmt.Sprintf("| P50 | %.2f |\n", s.P50LatencyMs))
		b.WriteString(fmt.Sprintf("| P95 | %.2f |\n", s.P95LatencyMs))
		b.WriteString(fmt.Sprintf("| P99 | %.2f |\n", s.P99LatencyMs))
		b.WriteString(fmt.Sprintf("| Max | %.2f |\n", s.MaxLatencyMs))

		b.WriteString("\n## Reliability\n\n")
		b.WriteString(fmt.Sprintf("- **Error Rate**: %.4f%%\n", s.ErrorRate*100))
	}

	if v := r.OverallSlaVerdict; v != nil {
		b.WriteString("\n## SLA Verdict\n\n")
		if v.Passed {
			b.WriteString("> ✅ All SLA thresholds met\n")
		} else {
			b.WriteString("> ⚠️ SLA violations detected\n\n")
			if len(v.Violations) > 0 {
				b.WriteString("| Metric | Threshold | Actual | Status |\n|---|---|---|---|\n")
				for _, viol := range v.Violations {
					b.WriteString(fmt.Sprintf("| %s | %.2f | %.2f | ❌ FAIL |\n",
						viol.Metric, viol.Threshold, viol.Actual))
				}
			}
		}
	}

	renderMarkdownPhases(&b, r)

	b.WriteString(fmt.Sprintf("\n---\n*Generated by `kates report export %s --format md`*\n", id))

	return b.String()
}

func renderMarkdownPhases(b *strings.Builder, r *client.Report) {
	if len(r.Phases) == 0 {
		return
	}
	b.WriteString("\n## Phase Breakdown\n\n")
	b.WriteString("| Phase | Status | Records | Throughput | P99 (ms) | Errors |\n|---|---|---|---|---|---|\n")
	for _, p := range r.Phases {
		name := p.Name
		if name == "" {
			name = "main"
		}
		status := "✓ " + p.Status
		if strings.EqualFold(p.Status, "FAILED") || strings.EqualFold(p.Status, "ERROR") {
			status = "✖ " + p.Status
		}
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s rec/s | %.2f | %.4f%% |\n",
			name, status, fmtNum(p.RecordsSent), fmtFloat(p.ThroughputRecPerSec, 1), p.P99LatencyMs, p.ErrorRate*100))
	}
}
