{{- if .Values.apiKey.enabled }}
{{- if not .Values.apiKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kates.fullname" . }}-api-key
  labels:
    {{- include "kates.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKey.secretKey | default "api-key" }}: {{ .Values.apiKey.value | default (randAlphaNum 32) | quote }}
{{- end }}
{{- end }}
