{{- if and .Values.kafka.ssl.enabled (or .Values.kafka.ssl.truststore.password .Values.kafka.ssl.keystore.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kates.fullname" . }}-kafka-ssl
  labels:
    {{- include "kates.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.kafka.ssl.truststore.password }}
  truststore-password: {{ .Values.kafka.ssl.truststore.password | quote }}
  {{- end }}
  {{- if .Values.kafka.ssl.keystore.password }}
  keystore-password: {{ .Values.kafka.ssl.keystore.password | quote }}
  {{- end }}
{{- end }}
