apiVersion: v1
kind: ServiceAccount
metadata:
  name: kates
  namespace: kates
  labels:
    app: kates
    app.kubernetes.io/name: kates
    app.kubernetes.io/part-of: klster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kates-chaos-role
  labels:
    app: kates
    app.kubernetes.io/name: kates
    app.kubernetes.io/part-of: klster
rules:
  - apiGroups: ["litmuschaos.io"]
    resources: ["chaosengines", "chaosexperiments", "chaosresults"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kates-chaos-role-binding
  labels:
    app: kates
    app.kubernetes.io/name: kates
    app.kubernetes.io/part-of: klster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kates-chaos-role
subjects:
  - kind: ServiceAccount
    name: kates
    namespace: kates
