apiVersion: v1
kind: Service
metadata:
  name: {{ include "headlamp.fullname" . }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "headlamp.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    name: http
